###########
# Authors
# florent.chuffard@univ-grenoble-alpes.fr
# slim.karkar@univ-grenoble-alpes.fr
# magali.richard@univ-grenoble-alpes.fr
# ---

########################################################
### Package dependencies /!\ DO NOT CHANGE THIS PART ###
########################################################

##  to generate the zip files that contain the programs or the results to submit to the Codalab platform.

if ( !exists(x = "params") ) {
    params                      <- NULL
}
if ( is.null(x = params$package_repository) ) {
    params$package_repository   <- "https://cloud.r-project.org"
}
if ( is.null(x = params$install_dependencies) ) {
    params$install_dependencies <- TRUE
}
print(params)
if ( params$install_dependencies ) {
    installed_packages <- installed.packages( )
    for (package in c("zip") ) {
        if ( !{ package %in% installed_packages } ) {
            print(x = paste("Installation of ", package, sep = "") )
            install.packages(
                pkgs = package
              , repos = params$package_repository
            )
        } else {
            print(x = paste(package, " is installed.", sep = "") )
        }
    }
    remove(list = c("installed_packages", "package") )
}
# -

####################################################
### Submission modes /!\ DO NOT CHANGE THIS PART ###
####################################################

# Participants can submit either
# - a code program, that will be executed on the challenge platform to generate the result (prediction) that will be scored against the ground truth
# - a result (prediction )file, that will be scored against the ground truth

###############################
### Code submission mode
# Participants need make a zip file (no constrain on the namefile) that contains :
#   - the file `metadata` that is generated by this script
#   - your code inside a *R* file named `program.R`. This file will be sourced and have to contain :
#   - a function `program` with `data_train` and `data_test` as argument : a matrix associated to your prediction.
#   - any other files that you want to access from your function `program` : during the ingestion phase (when your code is evaluated), the working directory will be inside the directory obtained by unzipping your submission.

###############################
### Result submission mode  
# Participants have to make a zip file (no constrain on the namefile), with your results as a matrix inside a rds file named `results.txt`.

##################################################################################################
### Submission modes /!\ EDIT THE FOLLOWING CODE BY COMMENTING/UNCOMMENTING THE REQUIRED PARTS ###
##################################################################################################


## define the public data set that you will use for your prediction :
data_train <- readRDS(file = "data_train.rds")
data_test <- readRDS(file = "data_test.rds")


# # Write a function to predict test set train set
#
# In the provided example, we use a naive method to generate the baseline prediction.


#' The prediction function
#'
#' @param data_train a matrix
#' @param data_test a matrix
#' @return the estimated parameters
#' @examples
#' program(data_train = data_train, data_test = data_test)
program <- function(data_train, data_test) {
    ##
    ## YOUR CODE BEGINS HERE
    ## 
    
    # use more represented categorie as model (NULL model)
    alpha = 1
    lambda = 0.01
    m = glmnet::glmnet(
      x=data.matrix(data_train[,-1]),
      y=data_train[,1],
      family="binomial",
      standardize=TRUE,
      lambda=lambda,
      alpha=alpha
    )
    data_pred  = predict(m, type="class", newx=data.matrix(data_test [,-1]))

    ##
    ## YOUR CODE ENDS HERE
    ##

    return(data_pred)
    
}

##############################################################
### Generate a submission file /!\ DO NOT CHANGE THIS PART ###
##############################################################

# we use the previously defined function 'program' to estimate A :
data_pred <- program(
  data_train = data_train,
  data_test = data_test
)

###############################
### Code submission mode

# we generate a zip file with the 'program' source code

if ( !dir.exists(paths = "submissions") ) {
    dir.create(path = "submissions")
}

# we save the source code as a R file named 'program.R' :
dump(
    list = c("program")
  , file = paste0("submissions", .Platform$file.sep, "program.R")
)

# we also generate the 'metadata' file
cat(
    "command: Rscript $program/program.R $input $output"
  , file = paste0("submissions", .Platform$file.sep, "metadata")
)

date_suffix = format(x = Sys.time( ), format = "%Y_%m_%d_%H_%M_%S")

# we create the associated zip file :
zip_program <- paste0("submissions", .Platform$file.sep, "program_", date_suffix, ".zip")
zip::zipr(
         zipfile = zip_program
       , files   = paste0("submissions", .Platform$file.sep, c("program.R", "metadata") )
     )
print(x = zip_program)

###############################
### Result submission mode  

#  Generate a zip file with the prediction

# + label="Submission - results zip file" echo=true results="verbatim"
if ( !dir.exists(paths = "submissions") ) {
    dir.create(path = "submissions")
}

## we save the estimated A matrix as a rds file named 'results.txt' :
# saveRDS(
#     object = data_pred
#   , file   = paste0("submissions", .Platform$file.sep, "results.rds")
# )

write.table(
  x=data_pred, 
  file= paste0("submissions", .Platform$file.sep, "results.txt"),
  quote=FALSE,
  row.names=FALSE,
  col.names=FALSE
)


## we create the associated zip file :
zip_results <- paste0("submissions", .Platform$file.sep, "results_", date_suffix, ".zip")
zip::zipr(
         zipfile = zip_results
       , files   = paste0("submissions", .Platform$file.sep, c("results.txt") )
     )
print(x = zip_results)

sessionInfo( )

###############################################################
### How to submit the zip file? /!\ DO NOT CHANGE THIS PART ###
###############################################################
#
# The code above generates the files *`r zip_program`*  and *`r zip_results`*  (the 1st one for code submission, the 2nd one for result submission).
#
# Submit the zip submission file on the challenge in the tab `Participate`, menu `Submit / View Results` menu, sub-menu `CHALLENGE #1`, by clicking the `Submit` button after filling out some metadatas.
#
# On the codalab challenge web page, The *STATUS* become : 
#   - Submitting
#   - Submitted	
#   - Running
#   - Finished
#
# When it’s finished :
#   - You refresh the page and see your score
#   - If enable, details for report could be downloaded by clicking *Download output from scoring step*.
#   - Some logs are available to download.
#   - Leader board is updated in the `Results` tab.
#


